{
 "title": "Back2Basics: Voting App Dashboard",
 "description": "Back2Basics: Amazon EKS Series by Romar Cablao",
 "tags": [
  "back2basics",
  "kubernetes",
  "voting-app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Voting App: Running Pods",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace, deployment) (\r\n  label_replace(\r\n    kube_pod_status_phase{namespace=\"voting-app\", phase=\"Running\"},\r\n    \"deployment\",\r\n    \"$1\",\r\n    \"pod\",\r\n    \".*-(vote|result|worker|postgresql|redis)-.*\"\r\n  )\r\n)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Voting App: Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_spec_taint{value=\"vote-app\"})"
    }
   ]
  },
  { "title": "Vote App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Vote App (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"voting-app\", pod=~\".*vote.*\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"voting-app\", deployment=~\".*vote\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vote App (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"voting-app\", pod=~\".*vote.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas{namespace=~\"voting-app\", deployment=~\".*vote\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "Result App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Result App (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"voting-app\", pod=~\".*result.*\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"voting-app\", deployment=~\".*result\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Result App (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"voting-app\", pod=~\".*result.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas{namespace=~\"voting-app\", deployment=~\".*result\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  { "title": "Worker App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Worker App (CPU)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"voting-app\", pod=~\".*worker.*\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"voting-app\", deployment=~\".*worker\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker App (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"voting-app\", pod=~\".*worker.*\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum by(deployment) (kube_deployment_status_replicas{namespace=~\"voting-app\", deployment=~\".*worker\"})",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}