apiVersion: v1
kind: ConfigMap
metadata:
  name: result-app
data:
  DB_HOST: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:       
  name: result-app
  labels:
    app: result-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      initContainers:
      - name: init
        image: busybox
        command:
        - sh
        - -c
        - sleep 30s
      containers:
      - name: result-app
        image: romarcablao/app-result:1.0
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: result-app
              key: DB_HOST
        resources:
          requests:
            cpu: 100m
            memory: 60Mi
          limits:
            cpu: 200m
            memory: 120Mi
      tolerations:
      - key: app
        operator: Equal
        value: vote-app
        effect: NoSchedule
      nodeSelector:
        app: vote-app
---
apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001